package br.com.alura.bytebank.exception

class FalhaNaAutentcacaoException: Exception("Falha na autenticação") {
}